# Generated by Django 4.2.7 on 2025-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx'), models.Index(fields=['assigned_user'], name='tasks_task_assigne_bbf369_idx'), models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'), models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx')],
            },
        ),
    ]
