# Generated by Django 4.2.7 on 2025-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
    ]
