version: '3.8'

services:
  users-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - users_data:/var/lib/postgresql/data

  tasks-db:
    image: postgres:15
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - tasks_data:/var/lib/postgresql/data

  notifications-db:
    image: postgres:15
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - notifications_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  users-service:
    build: ./backend/services/users-service
    depends_on:
      - users-db
    environment:
      - DEBUG=True
      - DB_HOST=users-db
    volumes:
      - ./backend/services/users-service:/app

  tasks-service:
    build: ./backend/services/tasks-service
    depends_on:
      - tasks-db
      - redis
    environment:
      - DEBUG=True
      - DB_HOST=tasks-db
      - REDIS_HOST=redis
      - USERS_SERVICE_URL=http://users-service:8001
    volumes:
      - ./backend/services/tasks-service:/app

  notifications-service:
    build: ./backend/services/notifications-service
    depends_on:
      - notifications-db
      - redis
    environment:
      - DEBUG=True
      - DB_HOST=notifications-db
      - REDIS_HOST=redis
      - USERS_SERVICE_URL=http://users-service:8001
    volumes:
      - ./backend/services/notifications-service:/app

  gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    depends_on:
      - users-service
      - tasks-service
      - notifications-service

volumes:
  users_data:
  tasks_data:
  notifications_data: